import './globals.css'
import Navbar from './components/Navbar'

import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
       <Navbar/>
       <main className='mx-12 mt-6'>

      {children}
       </main>
        </body>
    </html>
  )
}
