import './globals.css'
import styles from './page.module.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <nav>
          <ul className={styles.flex}>
          <li> <Link href="/">Home</Link></li>
          <li> <Link href="/about">About</Link></li>
          <li> <Link href="/users">Users</Link></li>
           
          </ul>
        </nav>
      {children}
        </body>
    </html>
  )
}
